Fixed image build.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,6 +42,9 @@ jobs:
       - name: Build Docker image
         run: docker build -t stevems/succession_moods:latest .
 
+      - name: Capture Docker build logs
+        run: docker build -t stevems/succession_moods:latest . || (echo "Docker build failed" && exit 1)
+
       - name: Push Docker image to Docker Hub
         run: |
           echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u stevems --password-stdin
