Fixed error build.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,7 +13,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout code
         uses: actions/checkout@v3
 
@@ -30,7 +29,6 @@ jobs:
       - name: Run flake8
         run: flake8 .
 
-
   deploy:
     runs-on: ubuntu-latest
     needs: test
@@ -40,10 +38,12 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Build Docker image
-        run: docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest .
+        run: |
+          docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest . || (echo "Docker build failed" && exit 1)
 
       - name: Capture Docker build logs
-        run: docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest . || (echo "Docker build failed" && exit 1)
+        run: |
+          docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest . || (echo "Docker build failed" && exit 1)
 
       - name: Push Docker image to Docker Hub
         run: |
